# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestFilterlaptops():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.set_page_load_timeout(30)
        self.driver.implicitly_wait(10)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_filterlaptops(self):
        self.driver.get("https://rtia.co.uk/")
        cookies_bar = self.driver.find_element(By.XPATH, "//div[@class='cookie-notice-container']")
        assert cookies_bar.is_displayed()
        self.driver.find_element(By.ID, "cn-accept-cookie").click()

        # self.driver.find_element(By.LINK_TEXT, "Ноутбуки и компьютеры").click()
        # self.driver.find_element(By.LINK_TEXT, "Ноутбуки").click()
        # element = self.driver.find_element(By.CSS_SELECTOR, ".sidebar-block:nth-child(3) > .sidebar-block__toggle")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        # element = self.driver.find_element(By.CSS_SELECTOR, "body")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element, 0, 0).perform()
        # self.driver.find_element(By.CSS_SELECTOR,
        #                          ".sidebar-block:nth-child(1) .ng-star-inserted:nth-child(1) > .checkbox-filter__link:nth-child(1)").click()
        # self.driver.execute_script("window.scrollTo(0,798)")
        # self.driver.find_element(By.CSS_SELECTOR,
        #                          ".checkbox-filter__item:nth-child(3) > .checkbox-filter__link").click()
        # self.driver.execute_script("window.scrollTo(0,342)")
        # self.driver.find_element(By.CSS_SELECTOR,
        #                          ".sidebar-block:nth-child(6) .checkbox-filter:nth-child(1) > .ng-star-inserted:nth-child(1) > .checkbox-filter__link:nth-child(1)").click()
        # self.driver.execute_script("window.scrollTo(0,342)")
        # self.driver.find_element(By.CSS_SELECTOR, ".catalog-grid__cell:nth-child(1) .goods-tile__title").click()
        # self.driver.execute_script("window.scrollTo(0,0)")
        # assert self.driver.find_element(By.CSS_SELECTOR,
        #                                 "div.title > h1.h2").text == " Ноутбук ASUS TUF Gaming F15 FX507VV-LP212 (90NR0BV7-M00EY0) Mecha Gray / 15.6\\\" IPS Full HD 144 Гц / Intel Core i7-13620H / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce RTX 4060, 8 ГБ /"

